[package]
name = "hyper_server"
version = "0.1.0"
authors = ["costajob <costajob@gmail.com>"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper.git" }
env_logger = "*"
num_cpus = "*"
